/*
A Basic logger function for debug messages.
*/
;(function(){
    /* The standard stdout to simulate text to screen without effort.*/

let wipeDocument = function(previous){
    console.log('Wipe document')
    let keep = this.keep;
    let dr = {};
    let store = {};
    for(let key of dockeys) {
        try{
            store[key] = document[key]
        }catch(e){
            console.warn('unprotected Document key', key)
        }

        if(keep.indexOf(key) > -1 ) {
            console.debug('Skipping Document', key)
        } else {
            let v = delete Document.prototype[key];
            v = delete window.document[key];
            dr[key] = v
            if( (document[key] == undefined) == false){
                console.warn('Cannot clean key', key)
            }
        }
    }
    this.docStore = store
}

Header.chainAppend('wipe', wipeDocument)


let dockeys = [
    'onreadystatechange',
    'onpointerlockchange',
    'onpointerlockerror',
    'onbeforecopy',
    'onbeforecut',
    'onbeforepaste',
    'onfreeze',
    'onresume',
    'onsearch',
    'onsecuritypolicyviolation',
    'onvisibilitychange',
    'oncopy',
    'oncut',
    'onpaste',
    'onabort',
    'onblur',
    'oncancel',
    'oncanplay',
    'oncanplaythrough',
    'onchange',
    'onclick',
    'onclose',
    'oncontextmenu',
    'oncuechange',
    'ondblclick',
    'ondrag',
    'ondragend',
    'ondragenter',
    'ondragleave',
    'ondragover',
    'ondragstart',
    'ondrop',
    'ondurationchange',
    'onemptied',
    'onended',
    'onerror',
    'onfocus',
    'oninput',
    'oninvalid',
    'onkeydown',
    'onkeypress',
    'onkeyup',
    'onload',
    'onloadeddata',
    'onloadedmetadata',
    'onloadstart',
    'onmousedown',
    'onmouseenter',
    'onmouseleave',
    'onmousemove',
    'onmouseout',
    'onmouseover',
    'onmouseup',
    'onmousewheel',
    'onpause',
    'onplay',
    'onplaying',
    'onprogress',
    'onratechange',
    'onreset',
    'onresize',
    'onscroll',
    'onseeked',
    'onseeking',
    'onselect',
    'onstalled',
    'onsubmit',
    'onsuspend',
    'ontimeupdate',
    'ontoggle',
    'onvolumechange',
    'onwaiting',
    'onwheel',
    'onauxclick',
    'ongotpointercapture',
    'onlostpointercapture',
    'onpointerdown',
    'onpointermove',
    'onpointerup',
    'onpointercancel',
    'onpointerover',
    'onpointerout',
    'onpointerenter',
    'onpointerleave',
    'onselectstart',
    'onselectionchange',
    'onfullscreenchange',
    'onfullscreenerror',
    'onwebkitfullscreenchange',
    'onwebkitfullscreenerror',


    'createElement',
    'createDocumentFragment',
    'createTextNode',
    'createCDATASection',
    'createComment',
    'createProcessingInstruction',
    'createAttribute',
    'createAttributeNS',
    'createEvent',
    'createRange',
    'createNodeIterator',
    'createTreeWalker',
    'createElementNS',
    'createExpression',
    'createNSResolver',


    'implementation',
    'URL',
    'documentURI',
    'compatMode',
    'characterSet',
    'charset',
    'inputEncoding',
    'contentType',
    'doctype',
    'documentElement',
    'xmlEncoding',
    'xmlVersion',
    'xmlStandalone',
    'domain',
    'referrer',
    'cookie',
    'lastModified',
    'readyState',
    'title',
    'dir',
    'body',
    'head',
    'images',
    'embeds',
    'plugins',
    'links',
    'forms',
    'scripts',
    'currentScript',
    'defaultView',
    'designMode',
    'anchors',
    'applets',
    'fgColor',
    'linkColor',
    'vlinkColor',
    'alinkColor',
    'bgColor',
    'all',
    'scrollingElement',
    'hidden',
    'visibilityState',
    'wasDiscarded',
    'fonts',
    'activeElement',
    'styleSheets',
    'pointerLockElement',
    'fullscreenElement',
    'adoptedStyleSheets',
    'children',
    'firstElementChild',
    'lastElementChild',
    'childElementCount',
    'fullscreenEnabled',
    'fullscreen',
    'rootElement',
    'importNode',
    'adoptNode',
    'open',
    'close',
    'write',
    'writeln',
    'hasFocus',
    'execCommand',
    'queryCommandEnabled',
    'queryCommandIndeterm',
    'queryCommandState',
    'queryCommandSupported',
    'queryCommandValue',
    'clear',
    'captureEvents',
    'releaseEvents',
    'exitPointerLock',
    'caretRangeFromPoint',
    'elementFromPoint',
    'elementsFromPoint',
    'prepend',
    'append',
    'querySelector',
    'querySelectorAll',
    'exitFullscreen',
    'evaluate',
    'constructor',
    'registerElement',
    'featurePolicy',
    'pictureInPictureElement',
    'pictureInPictureEnabled',
    'exitPictureInPicture',


    'getElementsByTagName',
    'getElementsByTagNameNS',
    'getElementsByClassName',
    'getElementsByName',
    'getSelection',
    'getElementById',


    'webkitCancelFullScreen',
    'webkitVisibilityState',
    'webkitHidden',
    'webkitIsFullScreen',
    'webkitCurrentFullScreenElement',
    'webkitFullscreenEnabled',
    'webkitFullscreenElement',
    'webkitExitFullscreen',
]


}).apply(Header)

