# Like a docker file for pyton mini build.
# Filepaths are relative.

ARG apples foo
ARG ls_com ls -lah
# green color
ARG ${apples} color

# ADD a key value, or apply a filename.
SETTINGS ../pybuild/${apples}.json
EXEC print('Python callout using Arg "apples": ${apples}')
EXEC myfunc(session)
PRINT echo statment with ${foo}

INCLUDE ./otherbuild.buildfile
# Copy a file to 'dest/foo.json'
COPY ../pybuild/foo.json
# copy a file into another destination
COPY ../pybuild/foo.json apples/otherfoo.json
# Copy this folder to 'dest/foo.json'
COPY ../pybuild/ /other/
# Copy buildfile dir content to dest
COPY . .
COPY ta tb tc td desta
#copy a backref targets,
# and anything in buildfile dir
# and anything in v1 examples to dest root
COPY ../pybuild/ . ../../v1/examples .

CMD ${ls_com}
PRINT echo statment with ${foo}
# Set the output directory all - or the current block process.
TARGET ../dist
# Set the current working directory.
CWD .
